######################################################################
# Automatically generated by qmake (3.0) Thu Dec 28 21:25:06 2017
######################################################################

TEMPLATE = app
TARGET = MopidyDisplay

DESTDIR = "build"

CONFIG += qt

QT += widgets

INCLUDEPATH += .
INCLUDEPATH += "lib/websocketpp-master/"
INCLUDEPATH += "lib/easywsclient/"

SOURCES += src/main.cpp
SOURCES += src/ws_client.cpp 
